version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: sudoku_postgres-14
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=sudoku